name: OpenEVT
version: "1.0.0"
slug: openevt
description: >-
  OpenEVT app. Connects to a compatible Envertech inverter and exposes
  its data to Home Assistant. 
  See https://github.com/brandon1024/OpenEVT?tab=readme-ov-file#prometheus--home-assistant-integrations
  for how to integrate it (requires configuration.yaml adjustments).
arch:
  - amd64
  - aarch64
ports:
  9090/tcp: 9090
options:
  address: ""
  serial_number: ""
schema:
  address: str
  serial_number: str
init: false
